### ISSUE TITLE
送信先が長期ダウンしている場合、ドメインソケットファイルがなくなりかつ送信キューバッファにデータが溜まっていない

### ISSUE THREAD

**Issue by habehabe** [plathome/pd-emitter#5]
●PD Emitterログファイル
............
I, [2015-08-08T21:01:43.583589 #23667]  INFO -- pdex#post:
{"transaction_id":"A629985848422574049"}
W, [2015-08-08T21:02:02.702635 #23673]  WARN -- pdex#post: 502 Bad
Gateway|http://testpd.plathome.com/api/v1/devices/01.f3ab3a.b36df007/message|{"__data__"=>"{\"deviceId\":\"d1d3b36df007\",\"memo\":\"FNO1
/opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in
`return!': 502 Bad Gateway (RestClient::BadGateway)
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in
`process_result'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in
`block in transmit'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:853:in
`start'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in
`transmit'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in
`execute'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in
`execute'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:69:in
`post'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/lib/helper_message_v1.rb:34:in
`post'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/lib/pd_pdex_v1_ob.rb:27:in
`block in post'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/lib/pd_pdex_v1_ob.rb:25:in
`each'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/lib/pd_pdex_v1_ob.rb:25:in
`post'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in
`run'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in
`invoke_command'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in
`dispatch'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in
`start'
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/bin/pd_pdex_v1_ob:5:in
`<top (required)>'
        from bin/stubs/pd_pdex_v1_ob:17:in `load'
        from bin/stubs/pd_pdex_v1_ob:17:in `<main>'
2015-08-08 21:02:02 +0900 [warn]: temporarily failed to flush the
buffer. next_retry=2015-08-08 21:01:44 +0900
error_class="RuntimeError" error="command returns 256:
bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb83a2a985653.log"
plugin_id="object:-232f79e6"
  2015-08-08 21:02:02 +0900 [warn]: suppressed same stacktrace
2015-08-08 21:02:02 +0900 fluent.warn: {"next_retry":"2015-08-08
21:01:44 +0900","error_class":"RuntimeError","error":"command returns
256: bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb83a2a985653.log","plugin_id":"object:-232f79e6","message":"temporarily
failed to flush the buffer. next_retry=2015-08-08 21:01:44 +0900
error_class=\"RuntimeError\" error=\"command returns 256:
bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb83a2a985653.log\"
plugin_id=\"object:-232f79e6\"","hostname":"HOST.example.org","tag":"fluent.warn","time":"2015-08-08
21:02:02 +0900"}
W, [2015-08-08T21:02:06.785695 #23694]  WARN -- pdex#post: 502 Bad
Gateway|http://testpd.plathome.com/api/v1/devices/01.f3ab3a.b36df007/message|{"__data__"=>"{\"deviceId\":\"d1d3b36df007\",\"memo\":\"FNO1
/opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in
`return!': 502 Bad Gateway (RestClient::BadGateway)
.......................................
        from /opt/pd/ruby/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pd-emitter-plugin-pdex-1.0.1/bin/pd_pdex_v1_ob:5:in
`<top (required)>'
        from bin/stubs/pd_pdex_v1_ob:17:in `load'
        from bin/stubs/pd_pdex_v1_ob:17:in `<main>'
2015-08-10 02:01:23 +0900 [warn]: failed to flush the buffer.
error_class="RuntimeError" error="command returns 256:
bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb85ef4b2932b.log"
plugin_id="object:-232f79e6"
2015-08-10 02:01:23 +0900 [warn]: retry count exceededs limit.
  2015-08-10 02:01:23 +0900 [warn]: suppressed same stacktrace
2015-08-10 02:01:23 +0900 [error]: throwing away old logs.
2015-08-10 02:01:23 +0900 fluent.warn:
{"error_class":"RuntimeError","error":"command returns 256:
bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb85ef4b2932b.log","plugin_id":"object:-232f79e6","message":"failed
to flush the buffer. error_class=\"RuntimeError\" error=\"command
returns 256: bin/stubs/pd_pdex_v1_ob post
var/pd_pdex_v1_ob/.20150808.q51ccb85ef4b2932b.log\"
plugin_id=\"object:-232f79e6\"","hostname":"HOST.example.org","tag":"fluent.warn","time":"2015-08-10
02:01:23 +0900"}
2015-08-10 02:01:23 +0900 fluent.warn: {"message":"retry count
exceededs limit.","hostname":"HOST.example.org","tag":"fluent.warn","time":"2015-08-10
02:01:23 +0900"}
2015-08-10 02:01:23 +0900 fluent.error: {"message":"throwing away old
logs.","hostname":"HOST.example.org","tag":"fluent.error","time":"2015-08-10
02:01:23 +0900"}

●ps ax | grep ruby
root@HOST:~# ps ax | grep ruby
 2720 ?        Sl    33:08 /opt/pd/ruby/versions/2.2.2/bin/ruby -S -x
bin/emitter -c conf/boot.conf --suppress-repeated-stacktrace
--no-supervisor --emit-error-log-interval 1 --inline-config   <source>
    type unix_unimsg     path
/pd-emitter/v1/localname/dev_le_0000001.sock     use_abstract true
key __data__     tag pd.pdex.v1.ob.01.f3ab3a.01a6c36a   </source>
<source>     type unix_unimsg     path
/pd-emitter/v1/localname/dev_le_0000004.sock     use_abstract true
key __data__     tag pd.pdex.v1.ob.01.f3ab3a.06db7c62   </source>
<source>     type unix_unimsg     path
/pd-emitter/v1/localname/dev_le_0000009.sock     use_abstract true
key __data__     tag pd.pdex.v1.ob.01.f3ab3a.64111936   </source>
<source>     type unix_unimsg     path
/pd-emitter/v1/localname/dev_le_0000010.sock     use_abstract true
key __data__     tag pd.pdex.v1.ob.01.f3ab3a.956a0a91   </source>
<source>     type unix_unimsg     path
/pd-emitter/v1/localname/dev_le_0000011.sock     use_abstract true
key __data__     tag pd.pdex.v1.ob.01.f3ab3a.b36df007   </source>
10132 pts/0    S+     0:00 grep ruby

●キューバッファDir

root@HOST:~# ls -lart /opt/pd/emitter/var/pd_pdex_v1_ob/
total 4
drwxrwxrwt 3 root root  60 Aug  7 10:27 ..
---------- 1 root root 214 Aug  9 05:28 .20150808.b51cd29959dc52879.log
drwxr-xr-x 2 root root  60 Aug 10 02:01 .
root@HOST:~#

**Comment by ma2shita** [comment]
Split this issue because two issues included.

**Comment by ma2shita** [comment]
closed

This issue move to https://ssl.plathome.co.jp/git/pd/pd-emitter-plugin-pdex/issues/2
