### ISSUE TITLE
README BOOTUP via supervisord cmd path error

### ISSUE THREAD

**Issue by mycowan** [plathome/pd-emitter#7]
re: OpenBlocks IoT バージョン - Linux obsbx1 3.10.17-poky-edison

失礼します。

READMEファイルでBOOTUP via supervisordの命令はちょっと違います。

それは、これを言う必要があります。

$git clone https://github.com/plathome/pd-emitter.git /opt/pd/emitter/deploy/dir

と

$cp /opt/pd/emitter/deploy/dir/share/pd-emitter-daemon/pd-emitter_supervisord.conf /etc/supervisor/cond.d/pd-emitter.conf

**Comment by mycowan** [comment]
Rubyのバージョンに問題があります。

ウィージー（すなわち。OpenBlocks IOT）でのRubyのバージョンに問題があります。

byebugはRubyのバージョン>=2.0.0が必要です。

root@obsbx1:/opt/pd/emitter/deploy/dir# bin/rake start
Could not find byebug-4.0.5 in any of the sources
Run `bundle install` to install missing gems.
root@obsbx1:/opt/pd/emitter/deploy/dir# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Using rake 10.4.2
Using columnize 0.9.0
Installing byebug 4.0.5 with native extensions

Gem::InstallError: byebug requires Ruby version >= 2.0.0.
An error occurred while installing byebug (4.0.5), and Bundler cannot continue.
Make sure that `gem install byebug -v '4.0.5'` succeeds before bundling.


けれども

ウィージーが1.9.3p194をより高いものサポートしていないと思います。

I ran apt-get install ruby 2.0.0. But /usr/bin shows only ruby1.8 and ruby1.9.1.

apt-get install ruby2.0.0をインストールしました。けど、/ usr/ binにruby1.8とruby1.9.1を示しています。

ここでチェックしました：

apt-cache madison ruby
      ruby |    1:1.9.3 | http://ftp.plathome.co.jp/pub/debian/ wheezy/main i386 Packages
ruby-defaults |    1:1.9.3 | http://ftp.plathome.co.jp/pub/debian/ wheezy/main Sources

**Comment by ma2shita** [comment]
mycowan-san;
Thx your entry issue, I confirm it, 100% accept.

I would split this issue that is 1.supervisor issue and 2.ruby version.

**Comment by mycowan** [comment]
Thank you very much for your quick answer.

よろしくお願いします。

c2 a1 56 69 76 61 20 6c 61 20 72 65 76 6f 6c 75 63 69 c3 b3 6e 21
